name: Safeimagekit.com
title: Safest website for your image processing needs. No files sent to server.
email: support@safeimagekit.com
description: Process your images safely, online for free using safeimagekit.com
baseurl: '' # the subpath of your site, e.g. /blog
url: https://safeimagekit.com # the base hostname & protocol for your site, e.g. http://example.com
siteurl: https://safeimagekit.com
twitter_username: jekyllrb
github_username: jekyll
favicon: /picture.png
logo: /picture.png
pwalogo: /picture.png
paginate: '12'
paginate_path: '/blog/page:num/'
alternateName: safeimagekit
theme: appscms-tools-theme
pwa: true
developerKey: AIzaSyD4wrfi4Ga-uTH2O4f6DFEhby1I68UQvN8
clientId: 862003477277-6c2jd8ggqvqpmbae6671umo1c83eidug.apps.googleusercontent.com
monumetricId: //monu.delivery/site/1/9/a31ae7-f174-41b2-b52e-15d95b855155.js
appId: 862003477277
internationalizationall: true
dropboxapikey: gdmcpa9nvv4xmih
safeui: true
disqus:
  shortname: utils
# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

production_google_analytics: 'UA-179965937-20'
development_google_analytics: ''

permalink: /blog/:title
